trigger:
  branches:
    exclude:
    - '*' 
    
pool:
  name: estore-devops

resources:
  pipelines:
  - pipeline: 'store-service'
    project: estore-devops
    source: '[YAML] - Build Store Service'
  - pipeline: 'estore-devops'
    source: 'Publish estore-devops artifact (drop)'

variables:
- group: 'Env vars - MUSW1-EN01 QA app deploy'

stages:
- stage: download_artifacts
  jobs:
  - job: download_artifacts
    steps:
    - download: store-service
    - download: estore-devops
- template: templates/deploy-to-env.yml
  parameters: 
    env: $(env)
    platform: $(platform)
    region: $(region)
    app: store
    app-zip-location: '$(Pipeline.Workspace)/store-service/zip/app.zip'
    app-config-location: '$(Pipeline.Workspace)/store-service/config'
    estore-devops-root: '$(Pipeline.Workspace)/estore-devops/drop'
    arm-client-id: '$(ARM_CLIENT_ID)'
    arm-client-secret: '$(ARM_CLIENT_SECRET)'
    arm-tenant-id: '$(ARM_TENANT_ID)'
    appconfig-endpoint: '$(appconfig_readonly_endpoint)'
    sp-service-conn-name: 'App deploy: MUSW1-EN01 QA'