trigger:
  branches:
    exclude:
    - '*' 
    
resources:
  pipelines:
  - pipeline: 'store-service'
    project: estore-devops
    source: '[YAML] - Build Store Service'
  - pipeline: 'estore-devops'
    source: 'Publish estore-devops artifact (drop)'

variables:
- group: 'Env vars - MUSW1-EN01 DEV app deploy'

stages:
- template: templates/deploy-to-env.yml