parameters:
  app: ''
  app-zip-location: ''
  app-config-location: ''
  estore-devops-root: ''
  sp-service-conn-name: ''
  env-var-group: ''

stages:
- stage: Deploy_app
  variables:
  - group: ${{ parameters['env-var-group'] }}
  jobs:
  - job: Deploy_app
    pool:
      name: estore-devops
    steps:
    - task: Bash@3
      inputs:
        filePath: ${{ parameters['estore-devops-root'] }}/scripts/upload_config.sh
        arguments: $(ARM_CLIENT_ID) $(ARM_TENANT_ID) $(ARM_CLIENT_SECRET) $(region) $(platform) ${{ parameters['app'] }} $(env) ${{ parameters['estore-devops-root'] }} ${{ parameters['app-config-location'] }}
    
    - task: AzureAppServiceManage@0
      inputs:
        azureSubscription: ${{ parameters['sp-service-conn-name'] }}
        Action: 'Stop Azure App Service'
        WebAppName: $(region)-$(platform)-${{ parameters['app'] }}-$(env)-as
        SpecifySlotOrASE: true
        ResourceGroupName: $(region)-$(platform)-$(env)-rg
        Slot: 'alt'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: ${{ parameters['sp-service-conn-name'] }}
        appType: 'webAppLinux'
        WebAppName: $(region)-$(platform)-${{ parameters['app'] }}-$(env)-as
        deployToSlotOrASE: true
        ResourceGroupName: $(region)-$(platform)-$(env)-rg
        SlotName: 'alt'
        packageForLinux: ${{ parameters['app-zip-location'] }}

    - task: AzureAppServiceManage@0
      inputs:
        azureSubscription: ${{ parameters['sp-service-conn-name'] }}
        Action: 'Start Azure App Service'
        WebAppName: $(region)-$(platform)-${{ parameters['app'] }}-$(env)-as
        SpecifySlotOrASE: true
        ResourceGroupName: $(region)-$(platform)-$(env)-rg
        Slot: 'alt'

    - task: Bash@3
      inputs:
        filePath: ${{ parameters['estore-devops-root'] }}/scripts/wait_for_service.sh
        arguments: https://$(region)-$(platform)-${{ parameters['app'] }}-$(env)-as-alt.azurewebsites.net/actuator/health/ping 600
        
    - task: AzureAppServiceManage@0
      inputs:
        azureSubscription: ${{ parameters['sp-service-conn-name'] }}
        Action: 'Swap Slots'
        WebAppName: $(region)-$(platform)-${{ parameters['app'] }}-$(env)-as
        ResourceGroupName: $(region)-$(platform)-$(env)-rg
        SourceSlot: 'alt'        

