parameters:
  env: ''
  platform: ''
  region: ''
  app: ''
  app-zip-location: ''
  app-config-location: ''
  estore-devops-root: ''
  arm-client-id: ''
  arm-client-secret: ''
  arm-tenant-id: ''
  appconfig-endpoint: ''
  sp-service-conn-name: ''
  env-var-group: ''

stages:
  - stage: Deploy_app
    jobs:
    - job: Deploy_app
      pool:
        name: estore-devops
      steps:
      - task: Bash@3
        inputs:
          filePath: ${{ parameters['estore-devops-root'] }}/scripts/upload_config.sh
          arguments: ${{ parameters['arm-client-id'] }} ${{ parameters['arm-tenant-id'] }} ${{ parameters['arm-client-secret'] }} ${{ parameters['region'] }} ${{ parameters['platform'] }} ${{ parameters['app'] }} ${{ parameters['env'] }} ${{ parameters['estore-devops-root'] }} ${{ parameters['app-config-location'] }}
      
      - task: AzureAppServiceManage@0
        inputs:
          azureSubscription: ${{ parameters['sp-service-conn-name'] }}
          Action: 'Stop Azure App Service'
          WebAppName: ${{ parameters['region'] }}-${{ parameters['platform'] }}-${{ parameters['app'] }}-${{ parameters['env'] }}-as
          SpecifySlotOrASE: true
          ResourceGroupName: ${{ parameters['region'] }}-${{ parameters['platform'] }}-${{ parameters['env'] }}-rg
          Slot: 'alt'

      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: ${{ parameters['sp-service-conn-name'] }}
          appType: 'webAppLinux'
          WebAppName: ${{ parameters['region'] }}-${{ parameters['platform'] }}-${{ parameters['app'] }}-${{ parameters['env'] }}-as
          deployToSlotOrASE: true
          ResourceGroupName: ${{ parameters['region'] }}-${{ parameters['platform'] }}-${{ parameters['env'] }}-rg
          SlotName: 'alt'
          packageForLinux: ${{ parameters['app-zip-location'] }}

      - task: AzureAppServiceManage@0
        inputs:
          azureSubscription: ${{ parameters['sp-service-conn-name'] }}
          Action: 'Start Azure App Service'
          WebAppName: ${{ parameters['region'] }}-${{ parameters['platform'] }}-${{ parameters['app'] }}-${{ parameters['env'] }}-as
          SpecifySlotOrASE: true
          ResourceGroupName: ${{ parameters['region'] }}-${{ parameters['platform'] }}-${{ parameters['env'] }}-rg
          Slot: 'alt'

      - task: Bash@3
        inputs:
          filePath: ${{ parameters['estore-devops-root'] }}/scripts/upload_config.sh
          arguments: https://${{ parameters['region'] }}-${{ parameters['platform'] }}-${{ parameters['app'] }}-${{ parameters['env'] }}-as-alt.azurewebsites.net/actuator/health/ping 600
          
      - task: AzureAppServiceManage@0
        inputs:
          azureSubscription: ${{ parameters['sp-service-conn-name'] }}
          Action: 'Swap Slots'
          WebAppName: ${{ parameters['region'] }}-${{ parameters['platform'] }}-${{ parameters['app'] }}-${{ parameters['env'] }}-as
          ResourceGroupName: ${{ parameters['region'] }}-${{ parameters['platform'] }}-${{ parameters['env'] }}-rg
          SourceSlot: 'alt'        

